### ISSUE TITLE
Firebase 7.7.0

### ISSUE THREAD

**Issue by iDevelopper** [firebase/quickstart-ios#1123]
Hi,

After pod update, 7.4.0 -> 7.7.0, nothing appear in dashboard. Am I missing something?

**Comment by paulb777** [comment]
Hi,

You might be running into https://github.com/firebase/firebase-ios-sdk/issues/7595 for which the workaround is adding the `-ObjC` option to the `Other Linker Flags` Build Setting.

**Comment by iDevelopper** [comment]
Thank you for your very quick response! It works. Can you explain why?

**Comment by paulb777** [comment]
Full details in the bug link above and associated CocoaPods bug.  

The short answer is that the Analytics library in Firebase 7.5.0 started using the `.xcframeworks` binary structure instead of the `.frameworks` binary structure to support development on ARM-based Macs. CocoaPods has a bug that is being fixed in its 1.10.2 release that it wasn't automatically adding the `-ObjC` option needed to link unreferenced symbols in Objective C libraries for `.xcframeworks`.

**Comment by iDevelopper** [comment]
Thanks a lot!
