### ISSUE TITLE
Firebase Analytics

### ISSUE THREAD

**Issue by iDevelopper** [firebase/quickstart-ios#1124]
Hi,
I am not sure I am writing in the right place.

Since I installed (updated) FirebaseAnalytics 7.7.0 (was 7.4.0) via Cocoapods v. 1.10.0 (and added the -ObjC linker flag), the Dashboard and Events views no longer display the number of users, the percentage and average time of view controllers...

The DebugView works.

**Comment by iDevelopper** [comment]
It seems there is a significant delay or someone has made a change. I updated my application yesterday (in France), I tested since this morning (7:00 am) and I now have (4:00 pm) the informations.

**Comment by morganchen12** [comment]
Analytics will avoid showing certain statistics when the amount of data is below a usage threshold. When shipping a new version of your app, you may have to wait some time before enough data becomes available for all statistics in the dashboard.

Closing this issue since it seems to have resolved itself, but feel free to re-open if that's not the case.
