### ISSUE TITLE
Multiple problems with FIRDynamicLinks

### ISSUE THREAD

**Issue by sertony** [firebase/quickstart-ios#120]
We experience several unexpected issues with FIRDynamicLinks starting since iOS 10 (or maybe new Firebase release).
 
I'd like to describe them with examples.
Let's see the link bellow. 
It's a deep link which should lead the user to the specific event inside the app.

https://pm75f.app.goo.gl/?link=https://dytnow.com/events/-KT8Sm5otxkMAqpqE6PV&ibi=com.dytnow.dyt&isi=1102521888&apn=com.dyt

1. If I click this link in Messages, Mail and Notes apps everything work perfectly (whether app installed or not).

2. If I paste this link in Safari instead of pushing me inside the application (which is installed) it suggests me to "Open this page in "AppStore"". Fine, I press the button and see the app in AppStore, click "Open" (since it's installed) and go inside the app. Unfortunately deep link is not passed, I can't see any parameters.

3. The link is posted in Twitter application. 
3a. Application is not installed. Pressing link I'm pushed to AppStore, installing app. Everything works fine, parameters are received.
3b. Application is installed. Pressing link I'm also pushed to AppStore, clicking "Open" and getting inside the app. Deeplink parameters are not received.

4. The links is posted in Facebook application.
4a. Application is not installed. Pressing link I see the alert message "Leave Facebook" and "Open app" button. Click on the button, nothing happens.
4b. Application is installed. Pressing link I see the same alert message, but by clicking "Open app" button it gets me inside the app and everything works fine.

5. The link is posted on web page. Application is not installed. Open the link inside the internal browser of any app (not Safari) it suggests you to go to AppStore, installing the app. At the end deep link parameters are not passed as well. if the same link is click on web page from Safari - everything works fine.

**Comment by ianbarber** [comment]
It feels like your issues come down to:

1) When the app is installed but you are redirected to the App Store, the deep link parameters aren't passed. 

I believe this is because the check for post-install deeplinks only happens the first times, so future opens wont check for the parameters, which sucks in cases the user is being sent to the app store. I'm not sure the best way to work around that, but one option might be to share to those networks a web link which has on it the dynamic link (which hopefully then behaves as intended). I know we've had discussions about this internally, but it wouldn't hurt to file a feature request here: https://firebase.google.com/support/contact/bugs-features

2)  In Facebook the open app button doesn't work when app not installed.

That feels like a bug - same link above. This is direct to the support team, so if you could include a screenshot and details on your app (primarily what methods you have set up in your app delegate) that would be great! 

Your case 5 does include something that sounds like it should work  to me (webview -> appstore -> new install), so might be worth a separate bug there. 

Sorry for bouncing you to another channel, but in the cases where some back and forth (and more details) are helpful, its better to go straight to the support team - hope that helps!
