### ISSUE TITLE
queryStarting / queryEqual / queryEnding doesn’t operate like how the documentation suggests

### ISSUE THREAD

**Issue by JannyKul** [firebase/quickstart-ios#142]
This could certainly be a gap in my knowledge so please excuse me if I have this wrong but the observed behaviour with queryStarting etc isn't what the documentation suggests.

Documentation suggestions:
1. queryStarting is equivalent to “greater than or equal to”
2. queryEqual is equivalent to “equal to”
3. queryEnding is equivalent to “less than or equal to”

Observed behaviour
1. queryStarting is equivalent to “greater than”
2. queryEqual doesn’t seem to work at all
3. queryEnding is equivalent to “less than”

tried on a few data structures but something like the following 

```
message_status
    userkeyblahblah
            messagekeyblah1
                    status_unread: 1
            messagekeyblah2
                    status_unread: 1
            messagekeyblah2
                    status_unread: 1
```

**This returns the 3 key/value's above**
`let messages = ref.child("message_status/userkeyblahblah/“).queryOrdered(byChild: "status_unread").queryStarting(atValue: 0.5, childKey: "status_unread")`

**This doesn't return anything (I would expect it to return all 3)**
`let messages = ref.child("message_status/userkeyblahblah/").queryOrdered(byChild: "status_unread").queryStarting(atValue: 1, childKey: "status_unread")`

**This doesn't return anything (I would expect it to return all 3)**
`let messages = ref.child("message_status/userkeyblahblah/").queryOrdered(byChild: "status_unread").queryEqual(toValue: 1, childKey: "status_unread")`

**Comment by morganchen12** [comment]
@mcdonamp FYI

**Comment by mikelehen** [comment]
Sorry for the super slow reply on this!

In regards to queryStarting bounds, your assumptions are right (queryStarting is >=, queryEqual is ==, and queryEnding is <=).  

The issue with your examples is the `childKey: "status_unread"` bit.  You should just remove that in these cases.  It's meant to be used as a "tie-breaker" when there are multiple keys that all have the specified starting value.  E.g. you could do `let messages = ref.child("message_status/userkeyblahblah/“).queryOrdered(byChild: "status_unread").queryStarting(atValue: 1, childKey: "messagekeyblah2")` to skip over messagekeyblah1.

This is mostly useful when you're implementing paging.  You can get the query value and key of the last item in the page and use it to create a query for the next page (though admittedly, that last item will end up repeated in the next page, since queryStarting performs >= instead of >).
