### ISSUE TITLE
IOS Having problem when upload symbol files for crash reporting

### ISSUE THREAD

**Issue by wding006** [firebase/quickstart-ios#178]
<img width="824" alt="screen shot 2016-12-09 at 6 21 04 pm" src="https://cloud.githubusercontent.com/assets/15316885/21045611/13ccc1b2-be3c-11e6-9b5f-355a2206b5e6.png">

I follow the guide to set up firebase crash reporting and when I run my project get above error

and following is my script
<img width="639" alt="screen shot 2016-12-09 at 6 32 35 pm" src="https://cloud.githubusercontent.com/assets/15316885/21046041/ada46758-be3d-11e6-85a8-018b5fed3f87.png">

**Comment by morganchen12** [comment]
From the [libcurl errors page](https://curl.haxx.se/libcurl/c/libcurl-errors.html):

>**CURLE_SSL_CONNECT_ERROR (35)**
>
>A problem occurred somewhere in the SSL/TLS handshake. You really want the error buffer and read the message there as it pinpoints the problem slightly more. Could be certificates (file formats, paths, permissions), passwords, and others.

Without additional info I can't help you further, but this issue is likely not a Firebase issue and should go on StackOverflow instead. Before filing a StackOverflow issue though I'd recommend you try to pinpoint the failure and not just upload a screenshot.
