### ISSUE TITLE
Firebase to Populate UIStackView or UICollectionView

### ISSUE THREAD

**Issue by troy21688** [firebase/quickstart-ios#225]
I have some previous experience in Android, and I utilized the FirebaseUI in Android to create a dynamic RecyclerView that updates based on real-time changes to the Firebase database.

Before I get too deep into learning the iOS equivalent, I was curious which would be the best to use in terms of Firebase and iOS (i.e. which iOS tool integrates best with Firebase):

*UIStackView (Preferred since it is new and has easier layout options).
*UICollectionView
*UiTableVIew

**Comment by morganchen12** [comment]
If you're targeting iOS versions where UIStackView is always available, then it's a good choice for small views of data that don't require view reuse.

Otherwise, UICollectionView gives the most customizability but UITableView is probably easier to use.

In general this is a question best fit for StackOverflow and not this issue tracker, since it isn't really a Firebase question.
