### ISSUE TITLE
Unknown Error Occurs on Topic Subscription 

### ISSUE THREAD

**Issue by yu840915** [firebase/quickstart-ios#242]
Firebase version: 3.15.0
Firebase Messaging version: 1.2.2
iOS version: 9+
Xcode version: 8.2.1
I have tried to subscribe to a topic named something like `sport|baseball` and since the SDK only allows [a-zA-Z0-9-_.~%], I encoded the name into `sport%7Cbaseball`. This works on Android; however, on iOS, it doesn't work. It showed following message on debugger 
```
 <FIRMessaging/WARNING> Failed to subscribe to topic Error Domain=com.google.fcm Code=0 "(null)"
```
and messages could not arrive.
Currently, our workaround is replacing `|` with `_`.

**Comment by rsattar** [comment]
I realize this is quite late on this issue, but I am able to subscribe to the topic `sport%7Cbaseball` using the Messaging SDK, and it is able to subscribe to that topic name successfully. I can also receive notifications to that topic name (note that topic name is now `sport%7Cbaseball`, and not `sport|baseball`).

If you happen to have updated to at least Firebase 4.x, would you give this a try again? Thanks!

**Comment by rsattar** [comment]
Apologies for the late response, this is fixed in https://github.com/firebase/firebase-ios-sdk/pull/220, and should be out in the next release of Firebase.

If you have more bugs to file about the SDK itself, please file them at https://github.com/firebase/firebase-ios-sdk/issues, instead of in quickstart-ios. Thanks! 👍
