### ISSUE TITLE
Handle message onbackground (swift 3 - iOS 10)

### ISSUE THREAD

**Issue by ulaserdegor** [firebase/quickstart-ios#279]
I want to process the database with future notification when the application is onbackround or closed. But I can only handle the incoming message when the application is open(foreground). 
Why can only handle the message when the application is foreground?

Is there a solution?

There is objective-c running code
[didReceiveRemoteNotification](https://gist.github.com/ulaserdegor/7fcc4b695e83198347ac67584c902468)

**Comment by rsattar** [comment]
You should be able to send a silent notification (i.e. `content-available: 1`) that can wake up your app in the background to perform simple tasks for a limited time. Are you not able to receive push notifications when your app is in the background? In particular, the "Background Modes" for your app should have "Remote Notification" checked in Xcode. Otherwise silent notifications cannot arrive when your app is in the background.

**Comment by ulaserdegor** [comment]
The application is notified when the background is running or closed. But I can not register the information in the notification database. Because the notification from the background does not call any method in the class.
What I want is; To save the notifications that come in while the application is closed to the database, and show them on the application's menu.
@rsattar

**Comment by rsattar** [comment]
I see, so whichever display notification that is shown while the app is not running, you _also_ want to have shown in a "notification history" type of list in the app?

If so, you are right — by its very nature of Apple push notifications, your app is not necessarily woken up for every notification received. However, on iOS 10, you can create a [Notification Service app extension](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/ModifyingNotifications.html#//apple_ref/doc/uid/TP40008194-CH16-SW1) for your app, which will allow your app to be woken up for a short time (currently about 30 seconds) in order to modify the payload. 

You don't have to modify the payload though; you can write out the incoming notification payload to your own file in a [shared app group](https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html), so your main app has access to it. Then the next time your main app starts up, you can read from the file and add it to the database.
