### ISSUE TITLE
Increase the Badge (swift 3 - iOS 10)

### ISSUE THREAD

**Issue by ulaserdegor** [firebase/quickstart-ios#280]
For example, 5 notifications. Normally, the badge needs to increase one by one for each notification. I can not do this because we can not control the message when the app is background.

There is objective-c running code
[didReceiveRemoteNotification](https://gist.github.com/ulaserdegor/7fcc4b695e83198347ac67584c902468)

**Comment by rsattar** [comment]
I think you're talking about supporting the ability to increase/decrease the badge count as an API, rather than setting an absolute value? This is technically possible, though since FCM is often not the *only* notification provider (or the developer is doing local notifications as well), it's possible to get the badge count into a state where it's out of sync with what is expected.

**Comment by ulaserdegor** [comment]
All I want is to get the current number of rosettes of the application like obj-c and increase it when it comes to its declaration. But I can not do this because I can not process the notifications from the background.

@rsattar

**Comment by DGP13** [comment]
How to handle increment and decrement badge using fcm notifcation ?
