### ISSUE TITLE
firebase sent message but device does not receive it 

### ISSUE THREAD

**Issue by AzAli71** [firebase/quickstart-ios#281]
hi , firebase panel shows my message sent completely but in here in client side we can't receive it , on the other hand I can't get FCM token anywhere but Always APNS token generates in 
"application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data)"
I have turned on push notification in Capabilities and I checked remote notification from background mode 
<img width="864" alt="screen shot 2017-05-27 at 5 58 17 pm" src="https://cloud.githubusercontent.com/assets/16123809/26521835/d91fb06e-4307-11e7-8610-5b3243993c66.png">

**Comment by alejandroivan** [comment]
@AzAli71 did you actually upload your push certificates (.p12 files) to the Firebase console? I've seen this error before, and tokens were successfully generated after uploading those.

**Comment by rsattar** [comment]
@AzAli71 Looks like your APNs set up is good, since you are receiving an APNs device token 👍 

The issue is here:
```Failed to fetch default token Error Domain=com.firebase.iid Code=0 "(null)"```

meaning that the SDK can't fetch a token or save it. Can you ensure that the Keychain is accessible in your app? And that you have network access?

To get additional debugging visible in the console (which would be helpful to diagnose what's happening), you can add `-FIRDebugEnabled` to your arguments passed on launch by going to you app scheme dropdown > Edit Scheme... > Run > Arguments tab.

![screen_shot_2017-07-12_at_1_22_17_pm](https://user-images.githubusercontent.com/423927/28138346-60a1029c-6705-11e7-907a-e43ae481ff18.png)

Also, what version of Firebase SDK are you using? Are you able to update to the latest one?

**Comment by AzAli71** [comment]
problem has fixed thanks a lot ;)

**Comment by iapyeh** [comment]
Hi AzAli71, May I know how do you fix it? I got the same issue. Thanks.
