### ISSUE TITLE
Intermediate page while opening a dynamic link

### ISSUE THREAD

**Issue by viralmoonlight** [firebase/quickstart-ios#291]
When a user clicks the top right button for universal link and supposedly decides to open that link in web, we noticed that the next time the user comes in, despite having a fallback url for ios, the redirect does not happen until the user clicks on "open in app" which then opens the redirect url. How do we get rid of this intermediate step?

![intermediatr](https://cloud.githubusercontent.com/assets/19497139/26734663/d9f81056-478c-11e7-8f66-66a34d0f6629.jpg)

**Comment by rsattar** [comment]
Unfortunately it's not possible to know whether the user has chosen to disable universal links for a particular domain/url, so the behavior can't be changed. 

The intermediate step here is because in certain types of web containers (e.g. a web page being shown inside another app like Facebook, or WhatsApp, Line, etc.), universal link support can be flaky and unreliable. Adding a step where the user _has_ to tap something explicitly usually can workaround that flakiness.
