### ISSUE TITLE
Notifications working on API but not on Firebase Console

### ISSUE THREAD

**Issue by LuisRodriguezLD** [firebase/quickstart-ios#319]
Not sure if this is the correct place but I am getting a really strange bug.

Short story, notifications sent from Firebase Console are not being delivered to my iOS app. I've tried specific device and all the apps with the same bundle.

However, if I send using `curl` on the terminal it works perfectly.
This is what I use and it works!

```
curl -X "POST" "https://fcm.googleapis.com/fcm/send" \
     -H "Authorization: key=MY_KEY" \
     -H "Content-Type: application/json" \
     -d $'{
  "notification": {
    "body": "Testing with direct FCM API",
    "title": "Test Message",
    "badge": "0",
    "sound": "default"
  },
  "registration_ids": [
"id here"
  ]
}'
```

But again, if I use the Firebase Console it does not work. I've only tested this on iOS. Any ideas?

**Comment by morganchen12** [comment]
>Not sure if this is the correct place but I am getting a really strange bug.

In the future please file these bugs on the [iOS SDK repo](https://github.com/firebase/firebase-ios-sdk). :)

cc @rsattar

**Comment by rsattar** [comment]
👍  to filing these in firebase/firebase-ios-sdk :)

@LuisRodriguezLD can you verify that this is the _same_ Sender ID in your Firebase project, as it is in your `GoogleService-Info.plist` file? Another way to test: Can you verify that `MY_KEY` exists in the same Firebase project as the one you're sending notifications from?

**Comment by LuisRodriguezLD** [comment]
> In the future please file these bugs on the iOS SDK repo. :)

Will do, sorry. 
Yes, I got `MY_KEY` directly from the Firebase console.

Here is the deal, I do not have a `GoogleService-Info.plist` file. I am using [Fuse](https://fusetools.com) and what I do is get the APN token from the device and transform it to a FCM token using the [batchimport API.](https://developers.google.com/instance-id/reference/server#create_registration_tokens_for_apns_tokens)

Then I just get the response and use _that_ as the token. It works using `https://fcm.googleapis.com/fcm/send` but not in the Firebase console.

I understand this is _probably_ not the best way to handle tokens but used to work a couple of weeks back, not sure what changed.

**Comment by LuisRodriguezLD** [comment]
[this](https://github.com/LuisRodriguezLD/Fuse-Firebase-Notifications/blob/master/Notifications.js) is _exactly_ what I'm doing

**Comment by rsattar** [comment]
Thanks @LuisRodriguezLD that info is crucial here, it turns out. So what's likely happening is that the batch import API doesn't know how to associate the FCM token with the Firebase project/app (see the `PROJECT_ID` key in the `GoogleService-Info.plist` in the console, so that relation is never created. 

The only way I can think of to do it currently would be to actually add the Firebase SDK to the Fuse app. I've never used Fuse before, but [it looks like this is possible](https://www.fusetools.com/docs/native-interop/facebook-login). For example, you would trigger Firebase using something like this:

```
[Foreign(Language.ObjC)]
extern(iOS) void Started(ApplicationState state)
@{
    [FIRApp configure];
    [FIRMessaging messaging].delegate = self;
@}
```

You'll have to add more foreign code into the js file though, adapting the [native integration instructions](https://firebase.google.com/docs/cloud-messaging/ios/client#initialize_firebase_in_your_app).

**Comment by LuisRodriguezLD** [comment]
I know very little of Objective C (which is why I had to come up with an alternative) but hey, I have to learn someday. I _will_ use foreign code. Thanks for your help, wish me luck!
