### ISSUE TITLE
MessagingExample compiling error

### ISSUE THREAD

**Issue by valeriyvan** [firebase/quickstart-ios#363]
MessagingExample/AppDelegate.m:45:28: Property 'delegate' not found on object of type 'FIRMessaging *'

**Comment by kroikie** [comment]
Hi @valeriyvan what version of the pod are you using? The current version is 2.0.5. Property `delegate` should be there, it is recommended to be used instead of `remoteMessageDelegate` which is [deprecated](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Messaging/Public/FIRMessaging.h#L308).
