### ISSUE TITLE
Device triggered notifications

### ISSUE THREAD

**Issue by av8ramit** [firebase/quickstart-ios#445]
I want to get my Swift code to send messages to a certain topic. I'm a bit confused on how to do this. StackOverFlow seems to have responses where they expose the API Key which I'm not sure is the best way to accomplish this. Is there any example where the iOS device triggers the notification. I have Console to device notifications working well.

Is [this](https://firebase.google.com/docs/cloud-messaging/ios/upstream) the approach I should be using? Or should I be using [Firebase cloud functions](https://firebase.google.com/docs/functions/)?

**Comment by morganchen12** [comment]
Most of the time when people want to do this they're sending notifications in response to some other write to the server--for example, a database write to some path that offline clients want to be notified for. In this case Cloud Functions is usually the best thing to use, since the function invocation can confirm the database write before sending the message, and is guaranteed to not send the message if for some reason the client's write fails.

**Comment by av8ramit** [comment]
@morganchen12 it worked! Thank you so much! FCM is awesome!
