### ISSUE TITLE
Could not locate configuration file: 'GoogleService-Info.plist'

### ISSUE THREAD

**Issue by sabhay1996** [firebase/quickstart-ios#5]
I'm unable to locate file or do I need to download my own ?
Could not locate configuration file: 'GoogleService-Info.plist'

**Comment by guydaher** [comment]
Follow step 4 under "Add Firebase to your app"
https://firebase.google.com/docs/ios/setup#prerequisites

**Comment by gumnym** [comment]
```
    NSString *filePath = [[NSBundle mainBundle] pathForResource:filename ofType:@"plist"];
    NSLog(@"file path: %@\n", filePath);
    FIROptions *options = [[FIROptions alloc] initWithContentsOfFile:filePath];
   
    options.deepLinkURLScheme = [[NSBundle mainBundle] bundleIdentifier];
    [FIRApp configureWithOptions:options];
```

With this I got error:

2017-05-28 16:39:26.892 OnTheRoadDEV[1238:2935821] file path: /var/containers/Bundle/Application/55CCA466-E876-4423-9509-9864615FFB2A/OnTheRoadDEV.app/GoogleService-InfoDEV.plist
2017-05-28 16:39:26.894 OnTheRoadDEV[1238] <Error> [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
2017-05-28 16:39:26.898 OnTheRoadDEV[1238] <Error> [Firebase/Analytics][I-ACS020006] Google App ID from GoogleService-Info.plist is empty. Please, define GOOGLE_APP_ID in GoogleService-Info.plist for Analytics to work reliably.
2017-05-28 16:39:26.906 OnTheRoadDEV[1238] <Error> [Firebase/Analytics][I-ACS025020] Analytics requires Google App ID from GoogleService-Info.plist. Your data may be lost. Google App ID has been changed. Original, new ID: (nil), 1:594395828869:ios:531162a2242a1e75
2017-05-28 16:39:26.910 OnTheRoadDEV[1238] <Notice> [Firebase/Analytics][I-ACS023007] Firebase Analytics v.4000000 started

**Comment by baolocdo** [comment]
The name must be "GoogleService-Info.plist". You are having "GoogleService-InfoDEV.plist" which is not exactly the same.

**Comment by gumnym** [comment]
So why there is possibility to init it with custom file, and what should I do if I want to have different configurations for different targets?

**Comment by baolocdo** [comment]
It's possible for other Firebase products but for Analytics, it requires a static file. That's why there is a warning message that there is a possibility that you may lose some events that happen before the FIRApp is configured.

**Comment by brunolemos** [comment]
For someone still having this error even after adding the file:

1. Add to the project
2. Click on it:

[![enter image description here][1]][1]

3. On the right sidebar from Xcode, mark the `Target Membership` option:

[![enter image description here][2]][2]


  [1]: https://i.stack.imgur.com/SIngc.png
  [2]: https://i.stack.imgur.com/kBc6k.png

**Comment by LearnSwiftNOVA** [comment]
@brunolemos That did it... Thanks!

**Comment by wafi-alshammari** [comment]
I have the same problem, I'm trying all solutions but still having it

**Comment by wafi-alshammari** [comment]
2017-09-27 20:54:21.315087 Health[4322:448801] [Accessibility] ****************** Loading GAX Client Bundle ****************
2017-09-27 20:54:21.409032 Health[4322:448833] [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
2017-09-27 20:54:21.409377 Health[4322:448833] [Firebase/Core][I-COR000005] No app has been configured yet.
2017-09-27 20:54:21.439282 Health[4322:448801] *** Terminating app due to uncaught exception 'com.firebase.core', reason: '`[FIRApp configure];` (`FirebaseApp.configure()` in Swift) could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/.'
*** First throw call stack:
(0x1897911b8 0x1881c855c 0x189791100 0x100188e18 0x1000fe0cc 0x1000fe224 0x18f6b86a4 0x18f8c8a98 0x18f8ce808 0x18f8e3104 0x18f8cb7ec 0x18b36792c 0x18b367798 0x18b367b40 0x18973eb5c 0x18973e4a4 0x18973c0a4 0x18966a2b8 0x18f6b17b0 0x18f6ac534 0x1000feba0 0x18864d5b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by suztomo** [comment]
@brunolemos Thank you! It worked. You saved me.

![image](https://user-images.githubusercontent.com/28604/31039890-94366754-a54f-11e7-835e-1af02035f010.png)

**Comment by lexers16** [comment]
@suztomo Oh thanks you a lot !! 
I was deadlock on this problem since one hour 😩

**Comment by shalem93** [comment]
@wafi-alshammari Did you find a solution? Am stuck as well and have similar logs...

**Comment by shalem93** [comment]
Okay it looks like wafi solved his problem: #331 

For me, the google plist file is correct and linked to Target. Still having issues. Any other ideas?

**Comment by anilabsinc-ajay** [comment]
Still Facing the same issue, If you are providing facility to user to use different plist for different configuration so why not for Analtyics

**Comment by Kulur** [comment]
↑↑↑ Absolutely this ↑↑↑
I am running into '[Fabric] GoogleService-Info.plist path unavailable' , because we use different plist file for each build configuration. Had to mess for few days when I was implementing uploading of dsyms and now, when swapping Crash Reporting for Crashlytics, same thing all over again. It's not really obvius, so how do I configure the path for GoogleService-Info.plist depending on build configuration??

**Comment by maxperry** [comment]
If you are using multiple schemes for the same target, you can edit each scheme and define a run script under Build -> Post-actions like the one below:

```
cp "${PROJECT_DIR}/GoogleService-Info.staging.plist" "${CONFIGURATION_BUILD_DIR}/MyApp.app/GoogleService-Info.plist"
```

This way the plist file specific to each configuration will be copied to the app bundle named as GoogleService-Info.plist so that Firebase will be able to find it.

Make sure to set "Provide build settings from" with your target when adding the run script.

**Comment by EricoGT** [comment]
Using `[FIRApp configureWithName:@"MY_APP_NAME" options:options];` worked for me.

**Comment by sfla** [comment]
Yup ^
When using `FirebaseApp.configure(options: firebaseOptions)` it logged that it couldn't find my GoogleService-Info.plist.
When using `FirebaseApp.configure(name:"SomeConfigName", options: firebaseOptions)` everything works fine.

**Comment by atereshkov** [comment]
@maxperry thanks for the solution! Looks like it's working.

**Comment by cooler333** [comment]
In `Build Settings` add `User-Defined Settings` Flag: for ex. GOOGLE_SERVICE_INFO_PLIST_NAME and customize it for schemes

![screen shot 2018-09-25 at 20 39 25](https://user-images.githubusercontent.com/2772537/46032082-57fc1100-c103-11e8-98fc-601bd8e3560d.png)

and add `Run Script Phase` in `Build Phases`
```
GOOGLE_SERVICE_INFO_PLIST_FROM="${PROJECT_DIR}/%YOUR_CUSTOM_PATH_TO_FOLDER%/${GOOGLE_SERVICE_INFO_PLIST_NAME}"
BUILD_APP_DIR="${BUILT_PRODUCTS_DIR}/${FULL_PRODUCT_NAME}"
GOOGLE_SERVICE_INFO_PLIST_TO="${BUILD_APP_DIR}/GoogleService-Info.plist"
cp "${GOOGLE_SERVICE_INFO_PLIST_FROM}" "${GOOGLE_SERVICE_INFO_PLIST_TO}"
```

**Comment by dconde7** [comment]
Place each GoogleService-Info.plist in subfolders.
<img width="254" alt="screen shot 2018-10-25 at 9 31 26 am" src="https://user-images.githubusercontent.com/887899/47503808-f7aedb00-d838-11e8-8445-22fc871f9a2f.png">

Configure firebase specifying the directory
<img width="996" alt="screen shot 2018-10-25 at 9 32 08 am" src="https://user-images.githubusercontent.com/887899/47503859-10b78c00-d839-11e8-9194-3fcbf95b9ed5.png">

**Comment by hiroyaiizuka** [comment]
I can overcome this problem, it was so hard... 


My cause was Google Service-info.plist had number because I downloaded so many  times like below.
GoogleService-info(8).plist  


After I delete (8) and delete old folder which is written 'GoogleService-info(8).plist ',  the problem  solved.  I hope this solution works for you.

**Comment by sridharrajagopal** [comment]
plist files are copied in binary form to the final build folder, which happens in an earlier phase than the runscript phase as suggested by @maxperry. I used a very similar approach - here's what I did:

Created different GoogleService-Info plist configurations for different targets in the same project. 

E.g. GoogleService-info-targetA.plist and GoogleService-info-targetB.plist

In the RunScripts section of each target build settings, 

cp -r "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/GoogleService-Info-targetA.plist" "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/GoogleService-Info.plist"

OR

cp -r "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/GoogleService-Info-targetB.plist" "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/GoogleService-Info.plist"

as the case may be. This preserves the binary form of the plist file in the build folder. 

Hope that helps! 
-Sridhar

**Comment by tomasnfranco** [comment]
> If you are using multiple schemes for the same target, you can edit each scheme and define a run script under Build -> Post-actions like the one below:
> 
> ```
> cp "${PROJECT_DIR}/GoogleService-Info.staging.plist" "${CONFIGURATION_BUILD_DIR}/MyApp.app/GoogleService-Info.plist"
> ```
> 
> This way the plist file specific to each configuration will be copied to the app bundle named as GoogleService-Info.plist so that Firebase will be able to find it.
> 
> Make sure to set "Provide build settings from" with your target when adding the run script.

This worked for me but Archive is now failing

**Comment by amit6061** [comment]
How can initialise the Firebase without GoogleService.plist  swift code?

**Comment by atereshkov** [comment]
@amit6061 you can't

**Comment by coreagame** [comment]
I Solved. 
If you are building with Unity3D.
Modify it like this: 
Open {Your XCode Project Dir}/Pods/Fabric/run file.
In 49 line.
ARGUMENTS="$API_KEY_ARG $BUILD_SECRET_ARG $@" 
->
ARGUMENTS="$API_KEY_ARG $BUILD_SECRET_ARG $1 '$2'"
