### ISSUE TITLE
Different results when running both iOS and Android versions of MLKit Text Recognition On-Device API with the same image as input

### ISSUE THREAD

**Issue by joaomelo81** [firebase/quickstart-ios#511]
When using the same image as input for the iOS and Android versions of MLKit Text Recognition On-Device API, I do get different results on the bounding boxes information (x,y,width,height) provided by each solution.

Please see below the original input image I've used for my tests and another image that shows the resulting text block's bounding boxes that were drawn based on the information provided by both of the Text Recognition on-device APIs (in blue is the iOS result and in red is the Android one):

[Original input image](https://i.stack.imgur.com/gp02T.jpg)

[Resulting bounding boxes](https://i.stack.imgur.com/GmGRQ.png)

Does anyone knows what could cause such differences between the results for iOS and Android versions of the API? I suspect they use different ML models for the text recognition / extraction of bounding boxes. If so, is there any chance of having both solutions running the same model in a near future since they are still on beta release?

Any thoughts are welcome!

**Comment by morganchen12** [comment]
Filed b/112423460 with the ML team, I'll let you know what they say. I suspect this is a bug or artifact of some offline model packaging caveats.

**Comment by morganchen12** [comment]
This issue is the result of the iOS and Android SDKs using different versions of the same OCR engine. It will be resolved in a future update, though not soon. In the meantime, both SDKs should continue to identify text correctly, though they may report slightly different bounding boxes.

If either SDK does not recognize text correctly, please open a new issue and I'll take a look. 

Thanks!
