### ISSUE TITLE
No such module 'Firebase DatabaseUI'

### ISSUE THREAD

**Issue by jweinst1** [firebase/quickstart-ios#53]
Just cloned the repo.

Tried running the swift example. In PostDataSource.swift, it raises this error. 

I noticed this happens with a lot of other Firebase apps. How do you fix the import issue?

**Comment by jfrancop** [comment]
I tried the Databases example and got the same error.
You need to 'pod install' on the folder of the project you want to run and also provide a 'GoogleServices-Info.plist" file. My simulator ran fine after that.

**Comment by sabhay1996** [comment]
No space between 'FirebaseDatabaseUI'

**Comment by BigSauce** [comment]
I'm experiencing the same issue.  Any ideas on how to fix this?

**Comment by BigSauce** [comment]
@jweinst1 @sabhay1996 This is an issue caused by the fact that we cloned the repo and opened the Xcode projects.  To build the projects successfully, we first have to run `pod install` in Terminal from within the project's directory.  Then open the workspace generated after running `pod install`, and build.  Should work after you do that.

Pod install downloads all needed dependencies and imports them into the generated xcode workspace.  So from there on, open the generated workspace instead of the individual project.

**Comment by jweinst1** [comment]
Ok this works for me now! Thanks
