### ISSUE TITLE
`pod install` issue

### ISSUE THREAD

**Issue by jenperson** [firebase/quickstart-ios#539]
When running `pod install` from any of the feature directories, I get the following error:

> [!] CocoaPods could not find compatible versions for pod "Firebase/Core":
>   In snapshot (Podfile.lock):
>     Firebase/Core (= 5.7.0)
> 
>   In Podfile:
>     Firebase/Core
> 
> None of your spec sources contain a spec satisfying the dependencies: `Firebase/Core, Firebase/Core (= 5.7.0)`.
> 
> You have either:
>  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.
> 
> Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

I'm using Cocoapods 1.5.3. Running `pod repo update` before running `pod install` does fix the issue, but if that is the command we want developers to run by default, we should update the README to reflect this. Otherwise we should update the Podfile.lock files.

**Comment by morganchen12** [comment]
I think it's best to use `pod install --repo-update` here, since

- People are most likely cloning this repo for the first time and installing pods, and
- The `Podfile.lock` is always updated to the latest Firebase pods, increasing the likelihood that anyone forking the repo doesn't have those specs yet.

Created #540 to fix this.
