### ISSUE TITLE
Results keeps changing in CameraViewController

### ISSUE THREAD

**Issue by zhouhao27** [firebase/quickstart-ios#541]
I'm using `recognizeTextOnDevice` in `CameraViewController`. The problem is the results on overlay view are always changing even I don't move the camera. Any idea on how to make the text stable?

**Comment by zhouhao27** [comment]
And by the way, why confidence in block is always nil?

**Comment by morganchen12** [comment]
There's going to be a substantial amount of changes in the text recognition area within the near future, which will hopefully address these issues. I unfortunately can't give a time frame for it, but since ML Kit is a beta product we're more free to make large breaking changes in shorter time frames.

Confidence is currently not available for on-device text recognition due to technical limitations in the OCR engine.
