### ISSUE TITLE
Dynamic Links on iOS12 only being triggered on the next fresh install, but not on the existing install

### ISSUE THREAD

**Issue by jml2014101** [firebase/quickstart-ios#556]
We are encountering a strange behavior on iOS 12.
We have been working on adding Firebase links into our application to allow a user to receive an email with a link, and when they tap the link, it will launch our application to a particular screen.

We were having trouble with getting a tapped link to launch our application on a device, and we tried a number of different things, and we discovered an odd behavior.

If we delete the application from the device, and then run the application from Xcode, then `application:openURL:options:` is called in our App Delegate with a Firebase URL (?).

Once the application is on the device, if we run the application again, then `application:openURL:options:` does not get called. We can do this several times. But as soon as we delete the app from the device and run it freshly, then `application:openURL:options:` is called (?!?)

If the application is running on device and I tap the link, then `application:continueUserActivity:restorationHandler:` is called with a Firebase URL.

But if the application is not running on device and I tap the link, then both `application:continueUserActivity:restorationHandler:` and `application:openURL:options:`  are not called any more. 

We are thoroughly confused at this point, and are thrashing against making this work. Can anyone provide any troubleshooting help or advice?

**Comment by ToddKerpelman** [comment]
It sounds like most of this is working as designed -- `applicationOpenURL:options` is only supposed to get called the first time an app is opened after clicking on a dynamic link. The rest of the time (on iOS 12, anyway) you should be getting your links through universal links, which goes through  `application:continueUserActivity:restorationHandler`.

The only part I'm curious about is that last one: When you say that if the app isn't running, then `application:continueUserActivity:restorationHandler:` isn't called. Do you mean this happens when you kill the app with the task manager, but the app is still installed on the device? And if so, can you share the code that's in that's handler? Can you double-check that this method returns true if it receives a dynamic link?

**Comment by jml2014101** [comment]
When I kill app and tap dynamic link, app is launched automatically.
But because both application:continueUserActivity:restorationHandler: and application:openURL:options: are not called any more, I can not get and handle real link :(

**Comment by ToddKerpelman** [comment]
Does your `aplication:didFinishLaunchingWithOptions:` method return `YES`? Apparently, if it doesn't, that can stop continueUserActivity from being called.

**Comment by jml2014101** [comment]
You are right.
For Facebook login, 'application:didFinishLaunchingWithOptions:' had following code:

    return [[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];

As I try to debug return value, it always returns NO.
So I have changed code as:

    [[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];
    return YES;

After this change, dynamic link is working correctly even if app was killed.
Thanks for your help 👍 谢谢
