### ISSUE TITLE
<FIRAnalytics/ERROR> Data loss

### ISSUE THREAD

**Issue by moesalih** [firebase/quickstart-ios#58]
I've configured my app according to the getting started guide, but I'm having some errors when using Firebase Analytics. When I log an Event, I get the following error:

```
<FIRAnalytics/ERROR> Data loss. Unable to update daily event counts. Name, error: screen, Error Domain=com.google.gmp.measurement.ErrorDomain Code=3 "Database operation "execute statement" failed with sqlite code 8 and error message "attempt to write a readonly database"" UserInfo={FIRAMonitorContext=execute statement,8,,, NSLocalizedDescription=Database operation "execute statement" failed with sqlite code 8 and error message "attempt to write a readonly database"}
<FIRAnalytics/ERROR> Transaction failed
```
Anyone know what the issue could be?

**Comment by baolocdo** [comment]
As stated in the error message "attempt to write a readonly database", your device may not allow writing to files. Can you check whether your device is set to read-only or whether it has run out of disk space?

**Comment by moesalih** [comment]
How does my device not allow writing to files?? This is on iPhone, and the device is not out of disk space. In fact, the problem happens on multiple devices, so I'm thinking it's either a problem with the library itself, or how the project is setup, but I followed the setup instructions exactly.

**Comment by baolocdo** [comment]
It was a guess since we could not reproduce the errors. Sometimes some devices may not allow writing to files for some reasons. It is interesting that you brought up the information that the problem happens on multiple devices. May I ask for more information such as OS versions, device types, and SDK version? Is it 100% reproducible?
Can you please turn on debug mode by using the argument flag -FIRAnalyticsDebugEnabled (for more information, go [here](https://firebase.google.com/docs/analytics/ios/start)) and give us more log messages to debug? There can be something wrong before that leads to such problem.

**Comment by miketsprague** [comment]
I also just had this happen but wasn't able to reproduce it.  I think Xcode had the app in a weird state (after I quit it, another instance of my app launched).  Not sure this is a firebase issue.

**Comment by myflashlab** [comment]
same problem described here: https://github.com/firebase/quickstart-ios/issues/34

**Comment by ianbarber** [comment]
Agree with the dupe, please track in #34
