### ISSUE TITLE
getting only full words from MLVision text recognizer

### ISSUE THREAD

**Issue by GioPalusa** [firebase/quickstart-ios#700]
Is there any way that I can guarantee that the words I'm getting is the full word? For instance, if I'm scanning a sum on an invoice that look like this "3554 28" can I somehow make sure that I don't get "554 28" or "54 28"? Since the words that are returned doesn't have a space before it.

**Comment by ulukaya** [comment]
Hi @GioPalusa, 
I'm not an ML expert but the base APIs won't be able to detect that. I suggest you guide the user to put the image into a bounding box as in https://github.com/firebase/mlkit-material-ios/tree/master/TranslateDemo

Otherwise you'd need a custom model or object detection to detect such mistakes.
