### ISSUE TITLE
Crashlytics reports not showing on the dashboard.

### ISSUE THREAD

**Issue by Neilfau** [firebase/quickstart-ios#791]
Crashes are not being reported on the dashboard even though with debugging enabled its says the report was delivered successfully. Ive pretty much tried everything possible and also every stack overflow suggestion going and it still doesn't show any crash reports. One thing of interest is event though the reports are not showing the crash statistics is being affected and decreasing every time i do a crash test. Ive attached the debug log.

Using iOS 12.4, iPhone XS & Xcode 11

`2019-09-19 11:16:50.884738+0100 Sprint-iOS[19664:1731535] [Crashlytics] Version 3.14.0 (144)
2019-09-19 11:16:50.884841+0100 Sprint-iOS[19664:1731535] [Crashlytics] Running on iPhone11,2, 12.4.1 (16G102)
    "com.twitter.crashlytics.ios" = "3.14.0";
2019-09-19 11:16:51.513922+0100 Sprint-iOS[19664:1731825] [Crashlytics:Crash:Reports] Packaged report with id '10eed41e8bcc46e2b2fba3d57a323c15' for submission
2019-09-19 11:16:51.514001+0100 Sprint-iOS[19664:1731825] [Crashlytics:Crash:Reports] Submitting report
2019-09-19 11:16:51.514133+0100 Sprint-iOS[19664:1731825] [Crashlytics:Crash:Reports] Submitting async /var/mobile/Containers/Data/Application/0481E460-7E05-4FD1-8C4E-485F602E00FD/Library/Caches/com.crashlytics.data/com.tricktrack.sprint/v3/prepared/8D821963-AF43-48B7-8CA5-BB01B805796A.multipartmime
2019-09-19 11:16:51.514981+0100 Sprint-iOS[19664:1731825] [Crashlytics:Crash:Reports:Event] Sending event.
2019-09-19 11:16:51.704549+0100 Sprint-iOS[19664:1731825] [Crashlytics:Crash:Reports] completed submission of /var/mobile/Containers/Data/Application/0481E460-7E05-4FD1-8C4E-485F602E00FD/Library/Caches/com.crashlytics.data/com.tricktrack.sprint/v3/prepared/02857779-A04A-4AF4-8E1F-A2473F6859DC.multipartmime
2019-09-19 11:16:51.705684+0100 Sprint-iOS[19664:1731825] [Crashlytics:Crash] report submission successful
2019-09-19 11:16:51.873884+0100 Sprint-iOS[19664:1731846] [Answers] Attempting to log app_crashed
2019-09-19 11:16:52.265520+0100 Sprint-iOS[19664:1731838] [Crashlytics:Crash:Reports] completed submission of /var/mobile/Containers/Data/Application/0481E460-7E05-4FD1-8C4E-485F602E00FD/Library/Caches/com.crashlytics.data/com.tricktrack.sprint/v3/prepared/8D821963-AF43-48B7-8CA5-BB01B805796A.multipartmime
2019-09-19 11:16:52.265749+0100 Sprint-iOS[19664:1731838] [Crashlytics:Crash] report submission successful`

Anyone have any suggestions?

**Comment by morganchen12** [comment]
Have you uploaded any symbol files to Crashlytics?

**Comment by Neilfau** [comment]
Not manually.... Ill try it though.

**Comment by elanovasconcelos** [comment]
any update on this? I have the same bug. Is there a version that I can use there isn't with the bug?

Actually I started to investigate why. In the beginning I wasn't getting any log about Crashlytics on Xcode. The reason was my old integration with Fabric. I had to remove the Fabric key that was in the plist and the key that was in the build fase run script. If I try to follow just the tutorial I was getting: 

**Mismatched configuration: Fabric entry found in app's Info.plist, but no API Key provided to the run script. If this app was set up in Fabric, or linked to Firebase, pass your API key to the run script as the first argument. If this app was onboarded via Firebase, remove the Fabric entry in your Info.plist**

After that I could start getting logs about Crashlytics. But now I think I have the same bug, because the logs say that it's working. (The log is from an old version, but the result in the same with the Crashlytics version 3.14.0):

**[Crashlytics] Version 3.13.4 (143)
[Crashlytics] Running on iPhone9,3, 12.3.1 (16F203)
[Answers] Initialized
[Fabric] Initialized with kit versions: {
    "com.twitter.answers.ios" = "1.4.1";
    "com.twitter.crashlytics.ios" = "3.13.4";
    "io.fabric.sdk.ios" = "1.10.2";

[Crashlytics:Crash:Reports] Packaged report with id '9e06ebd6aae240108cead10eafda56e1' for submission
[Crashlytics:Crash:Reports] Submitting report
[Crashlytics:Crash:Reports] Submitting async /var/mobile/Containers/Data/Application/744E4402-3A20-4D6C-9E8A-972F37050CBA/Library/Caches/com.crashlytics.data/APP_NAME/v3/prepared/9FDBC984-17B9-408A-84FE-77BF8EE7C5C6.multipartmime
[Crashlytics:Crash:Reports:Event] Sending event.
[Crashlytics:Crash:Reports] completed submission of /var/mobile/Containers/Data/Application/744E4402-3A20-4D6C-9E8A-972F37050CBA/Library/Caches/com.crashlytics.data/APP_NAME/v3/prepared/9FDBC984-17B9-408A-84FE-77BF8EE7C5C6.multipartmime
[Crashlytics:Crash] report submission successful**

**Comment by morganchen12** [comment]
@elanovasconcelos, I'm assuming you have all the dSYMs uploaded as well? I initially had assumed that the root of this issue was Crashlytics console not showing unsymbolicated crashes, but since you mentioned Fabric migration it's possible there's something else going on.

**Comment by elanovasconcelos** [comment]
should I have to upload even for a debug version? The isn't any missing dSYMs listed on firebase.

I always upload the dSYMs file after send to Apple. I have to send a new version, so now I'll send with Crashlytics version 3.14.0 and hope that now it's only missing the dSYMs file. =(

**Comment by morganchen12** [comment]
Debug versions shouldn't need a dSYM file if the debug information isn't stripped out of the binary.

@TKBurner have you seen this issue before?

**Comment by kevinkokomani** [comment]
There are still some instances where a crash report can fail to be sent to the dashboard even when there are no missing dSYMs and the report upload looks successful as per the logs. @elanovasconcelos, @Neilfau could you reach out to support@fabric.io so we can dig into more logs and potentially some project files?

**Comment by elanovasconcelos** [comment]
sure, I'll send an email now.

**Comment by morganchen12** [comment]
Closing this issue since it's no longer actionable here. If you're unable to see crashes in your dashboard and you've completed all migration steps, please [file a support ticket to Firebase](http://firebase.google.com/support).

**Comment by Rahulkhandal** [comment]
@morganchen12 I am getting the same exact issue of @elanovasconcelos. Can u please help me to solve this

**Comment by Rahulkhandal** [comment]
@elanovasconcelos Bro, Can u please let me know, how you resolved this

**Comment by elanovasconcelos** [comment]
@Rahulkhandal hi, sorry for the late response. I fix my bug. Did you migrate from Fabric to Firebase? That was my scenario.

I may be crazy, but I think an old tutorial of how to migrate Fabric to Firebase said to remove the line: Fabric.with([Crashlytics.self]), after added it back it start working again. Today the tutotial is just a website migration. But before that I tried a lot of things. So please try this:

- before all, did you get any log about Crashlytics on Xcode? (like crash sent, version etc)
- update the pods to the last version
- unlink the Fabric -> Firebase integration (Settings -> Project settings -> Fabric)
- on Xcode: make sure the Run script is the last one in the list and add $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH) to the Input Files
- make sure that the Fabric key is in the run script
- make sure that Fabric key is on the info.plist
- make sure that you're calling: Fabric.with([Crashlytics.self])
- link the Fabric -> Firebase integration on the Fabric website

I hope that this can help. =)

**Comment by Rahulkhandal** [comment]
@elanovasconcelos Thanks for your response Bro. Yes I migrated from fabric to firebase . I am getting same issue what u described. I will try what u said.

Just a confustion over your solution: Fabric.with([Crashlytics.self]) should be removed right ?

**Comment by elanovasconcelos** [comment]
@Rahulkhandal I talked with Fabric support and it was one of the suggestion that they give to me and I did it. So I added on the list.
