### ISSUE TITLE
Storage SDK: Resume upload session after closing/opening the app?

### ISSUE THREAD

**Issue by myflashlab** [firebase/quickstart-ios#89]
On the Android side of your SDK, you have a uploadsession URI thing which we can save and resume later even when we are closing the app and resuming a day later!

We don't seem to be finding this feature on the iOS side. So, I wonder if this feature is supposed to be added to the iOS SDK in future or not? If yes, could I ask if you have a timeframe for it?

You know, building an app on both platforms using Firebase SDK will be very confusing if the iOS side is functioning differently compared to the Android side.

**Comment by mcdonamp** [comment]
Long story short is that it's more important on Android (since things like screen rotations cause an activity change, while on iOS they don't), so we implemented it first there. Long term, we plan on having fully backgrounded resumable uploads, so even if the phone dies, the upload can be resumed automatically if desired.

Agreed that it's confusing to have features on one platform and not the other though, so we're planning to resolve it.

**Comment by johnpaulmanoza** [comment]
Any updates about this?

**Comment by mcdonamp** [comment]
@johnpaulmanoza nothing new unfortunately, we're spending the majority of our time on performance improvements and globalizing the service vs new client features. Happy to notify people and get feedback from you when we move back to client feature work.

**Comment by dedan** [comment]
Maybe now any updates on this?

**Comment by mcdonamp** [comment]
We've got https://github.com/firebase/firebase-ios-sdk/issues/147 tracking this. Please add any comments/API suggestions there. Pull requests are also always welcome :)
